version: "3.0"
services:
  data-plotter:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "data-plotter"
      MODULE_TYPE: "Processing"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      X_AXIS_DATA: "timestamp"
      Y_AXIS_DATA: "temperature"
      SAMPLE_SIZE: 100
      X_AXIS_LABEL: "Timestamp"
      Y_AXIS_LABEL: "Sensor Data"
      GRAPH_TITLE: "Sensor Data Graph"
      GRAPH_COLOR: "red"
      GRAPH_LINESTYLE: "dashed"
      GRAPH_MARKER: "o"
      GRID_LINES: "both"
      OUTPUT_LABEL: "chart-file"
    ports:
      - 80:80
